"""add album category

Revision ID: 11dd73e27223
Revises: 04bdb5efdfe9
Create Date: 2020-01-22 11:46:47.204725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11dd73e27223'
down_revision = '04bdb5efdfe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('category', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'category')
    # ### end Alembic commands ###
